// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuLcZ8VCqAeVNHCP8kGAplXX6N9lXpcuQ',
    appId: '1:592785264800:web:cd8646e5b7e329899f39c5',
    messagingSenderId: '592785264800',
    projectId: 'v-kayplan-travel-app',
    authDomain: 'v-kayplan-travel-app.firebaseapp.com',
    storageBucket: 'v-kayplan-travel-app.firebasestorage.app',
    measurementId: 'G-442QBB16WK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS8TrGuMlVZCWmmATW8vn6KApYYv_tTFs',
    appId: '1:592785264800:android:7967e23ec49105829f39c5',
    messagingSenderId: '592785264800',
    projectId: 'v-kayplan-travel-app',
    storageBucket: 'v-kayplan-travel-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMQDBhZhwUIm_6_pzufJWG6wgsBGhbp8I',
    appId: '1:592785264800:ios:64a3b058642613e79f39c5',
    messagingSenderId: '592785264800',
    projectId: 'v-kayplan-travel-app',
    storageBucket: 'v-kayplan-travel-app.firebasestorage.app',
    iosBundleId: 'com.example.tropicaguideApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMQDBhZhwUIm_6_pzufJWG6wgsBGhbp8I',
    appId: '1:592785264800:ios:64a3b058642613e79f39c5',
    messagingSenderId: '592785264800',
    projectId: 'v-kayplan-travel-app',
    storageBucket: 'v-kayplan-travel-app.firebasestorage.app',
    iosBundleId: 'com.example.tropicaguideApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuLcZ8VCqAeVNHCP8kGAplXX6N9lXpcuQ',
    appId: '1:592785264800:web:3f2460e25f6abf9a9f39c5',
    messagingSenderId: '592785264800',
    projectId: 'v-kayplan-travel-app',
    authDomain: 'v-kayplan-travel-app.firebaseapp.com',
    storageBucket: 'v-kayplan-travel-app.firebasestorage.app',
    measurementId: 'G-TDQJBMCZM6',
  );
}
